version: '3.8'

services:
  stock-app:
    build: ./Dockerfile
    image: stock-app:latest
    ports:
      - "8080:80"
    depends_on:
      - postgres-dev
      - postgres-prod

  postgres-dev:
    image: postgres:13
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data

  postgres-prod:
    image: postgres:13
    environment:
      POSTGRES_DB: prod_db
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_password
    volumes:
      - postgres-prod-data:/var/lib/postgresql/data

volumes:
  postgres-dev-data: ./data
  postgres-prod-data:
