version: '3.8'

services:
  #stock-app:
  #  build: ./Dockerfile
  #  image: stock-app:latest
  #  stdin_open: true # docker run -i
  #  tty: true        # docker run -t
  #  volumes:
  #    - .:/app
  #  ports:
  #    - "8080:80"
  #  depends_on:
  #    - postgres-dev
  #    - postgres-prod
  
  postgres-dev:
    image: postgres
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres-dev-data:

